### ISSUE TITLE
Peak min/max torque units on display (non-metric unit selection) read in metric (N*m)

### ISSUE THREAD

**Issue by kdjcollins** [amund7/ScanMyTesla#10]
![screenshot 114](https://user-images.githubusercontent.com/32053148/30530228-d20fe5d2-9bf9-11e7-919f-d495308228c0.png)
Non-metric torque units are properly reporting  (lbf*ft) on display and in csv file, however when "double-clicking" the front or rear torque parameter on display, the peak min/max torque units display improperly in newton*meter instead. See screenshot of video file. Apparently mp4 files can be uploaded on this site. If you look at the reported front and rear torque vales on the screenshot, this instant is the max value of each, but the min/max values in parenthesis instead show values 1/0.73 x actual, meaning the max values are in N*m instead of lbf*ft. The log (raw and csv, xls) for this run were attached with my previous post tonight, so I didn't want to duplicate). Thanks

**Comment by amund7** [comment]
Fixed in upcoming version
