### ISSUE TITLE
Several parameters removed from "PERF" Tab- Current, Speed, Watt Pedal - how to get back?

### ISSUE THREAD

**Issue by kdjcollins** [amund7/ScanMyTesla#16]
From version a few weeks ago, several parameters have removed from "PERF" Tab- Current, Speed, Watt Pedal %- how to get them back? How to add front & rear RPM and delete consumption, etc?

**Comment by amund7** [comment]
Please don't file issues for questions, use e-mail or the facebook page instead.

You will find all items in the 'all' tab, you can select (click) and copy (long-press) from there. Go to the target tab and Paste in the right side menu.

**Comment by kdjcollins** [comment]
Ok got it. Thanks. 

Ken Collins
