### ISSUE TITLE
peak min/max hp and torque values displayed

### ISSUE THREAD

**Issue by kdjcollins** [amund7/ScanMyTesla#17]
Latest release peak min/max torque values display for front and rear motor - both front & rear read the actual peak torque of the REAR motor  (in agreement with the csv log), rather than each displaying their own peak max torque values. Also, front hp and rear hp both read combined peak hp (all 3, front, rear, and combined read the same max value 635 hp, in agreement with the csv log. I attached excel file since can't attach csv and I didn't log raw. Also attached is screen shot of display at time of peak hp. It can be seen that peak front = peak rear = peak combined hp. I realize that you have a rear drive Tesla so can't see this issue on yours. Thanks!

[Perf 2017-09-25 05-32-15.xlsx](https://github.com/amund7/ScanMyTesla/files/1330131/Perf.2017-09-25.05-32-15.xlsx)
![screenshot 142](https://user-images.githubusercontent.com/32053148/30819131-9ec0591c-a1d2-11e7-875c-4af5d83b142b.png)

**Comment by amund7** [comment]
Absolutely right, I made a mistake when converting the max/min values. Fixed, will release an update now.

**Comment by kdjcollins** [comment]
Works great!

Ken Collins
